all: Bellman-Ford2.cpp
	g++ -std=c++11 Bellman-Ford2.cpp -o a.out
	./a.out

B1: Bellman-Ford.cpp
	g++ -std=c++11 Bellman-Ford.cpp -o a.out
	./a.out

B2: Bellman-Ford2.cpp
	g++ -std=c++11 Bellman-Ford2.cpp -o a.out
	./a.out
